name: CI
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  Ubuntu:
      name: RUN CI
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: superfly/flyctl-actions@1.1
          with:
            args: "deploy"